name: Deploy to Hosting
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: SSH Build Project 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd lovely-pets
            git config --global --add safe.directory /${{secrets.SSH_USERNAME}}/lovely-pets
            git clean -d -f .
            git pull origin main
            yes | cp -f .env.example .env
            chmod -R 777 storage/
            chmod -R 777 storage/logs
            chmod -R 777 storage/framework
            chmod -R 777 bootstrap/cache
            chmod -R 777 vendor/composer
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{secrets.DB_PASSWORD}}/ ' .env
            vendor/bin/sail up -d
            vendor/bin/sail composer install
            vendor/bin/sail composer dump-autoload
            vendor/bin/sail artisan key:generate
            vendor/bin/sail artisan optimize
            vendor/bin/sail artisan migrate
