name: Deploy to Hosting
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Node Build Project
        run: npm run build

      - name: SSH Build Project 
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            chmod -R 777 lovely-pets
            cd lovely-pets
            git config --global --add safe.directory /${{secrets.SSH_USERNAME}}/lovely-pets
            git clean -d -f .
            git reset --hard
            git pull origin main
            yes | cp -f .env.example .env
            sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{secrets.DB_PASSWORD}}/ ' .env
            vendor/bin/sail composer install
            vendor/bin/sail composer dump-autoload
            vendor/bin/sail artisan key:generate
            vendor/bin/sail artisan migrate
            vendor/bin/sail artisan optimize
            vendor/bin/sail up -d
